- name: Install Kubernetes (MicroK8s)
  hosts: raspis
  tasks:
    - name: Install snap
      become: yes
      shell: apt install -y snapd

    - name: Install core
      become: yes
      shell: snap install core

    - name: Install MicroK8s
      become: yes
      shell: snap install microk8s --classic --channel=1.25

    - name: Join group
      become: yes
      shell: /usr/sbin/usermod -a -G microk8s `whoami`

    - name: Setup kubectl
      become: yes
      shell: |
        mkdir ~/.kube
        microk8s config > ~/.kube/config

    - name: Set owner
      become: yes
      shell: /usr/bin/chown -f -R `whoami` ~/.kube
